name: Semantic Release
on:
  push:
    branches:
      - main
jobs:
  semantic-release:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.15.0
      - name: check out code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
  merge:
    needs: semantic-release
    runs-on: ubuntu-20.04
    steps:
      - name: merge to develop
        uses: bambamboole/gha-upmerge@master
        with:
          from_branch: 'master'
          to_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}